[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/e-commerce.jar"

[variables]
MAVEN_OPTS = "-Xmx1024m -XX:MaxMetaspaceSize=512m"
