[build]
builder = "NIXPACKS"
buildCommand = "mvn clean package -DskipTests"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "java -Dserver.port=$PORT -jar target/e-commerce.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
