[build]
builder = "DOCKERFILE"
dockerfilePath = "Ecommerce-Backend/Dockerfile"

[deploy]
startCommand = "java -Xmx512m -Xms256m -jar app.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
